.\" Copyright (C) 2001 Kazu Yamamoto
.\" All rights reserved.
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\"
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer.
.\" 2. Redistributions in binary form must reproduce the above copyright
.\"    notice, this list of conditions and the following disclaimer in the
.\"    documentation and/or other materials provided with the distribution.
.\" 3. Neither the name of the team nor the names of its contributors
.\"    may be used to endorse or promote products derived from this software
.\"    without specific prior written permission.
.\"
.\" THIS SOFTWARE IS PROVIDED BY THE TEAM AND CONTRIBUTORS ``AS IS'' AND
.\" ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
.\" IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
.\" PURPOSE ARE DISCLAIMED.  IN NO EVENT SHALL THE TEAM OR CONTRIBUTORS BE
.\" LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
.\" CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
.\" SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR
.\" BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
.\" WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE
.\" OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN
.\" IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
.TH PGPDUMP 1 "September 25, 2026"
.SH NAME
pgpdump - A PGP packet visualizer
.\"
.SH SYNOPSIS
pgpdump
.RI [ options ]
.RI [ PGPfile ]
.\"
.SH DESCRIPTION
The
.B pgpdump
is a PGP packet visualizer which displays the packet format
of OpenPGP (RFC 9580 and RFC 4880) and PGP version 2 (RFC 1991).
It also displays the LibrePGP extensions generated by GnuPG:
version 5 keys and signatures, the OCB Encrypted Data packet,
and version 5 Symmetric-Key Encrypted Session Key packets.
If
.I PGPfile
is not specified, the standard input is read.
Both binary and ASCII armored input are accepted.
.PP
The options are as follows:
.TP 8
.B \-a
Accepts ASCII input only.
.TP 8
.B \-g
Selects alternate dump format, which displays printable characters
as they are and others as \exNN (like GnuPG).
.TP 8
.B \-h
Displays a help message.
.TP 8
.B \-i
Dumps multi-precision integers and fixed-length key material.
.TP 8
.B \-l
Dumps literal packets.
.TP 8
.B \-m
Dumps marker packets.
.TP 8
.B \-p
Dumps private packets.
.TP 8
.B \-u
Displays UTC time.
.TP 8
.B \-v
Displays the version.
.\"
.\"
.SH OUTPUT
Each packet starts with a line such as
.PP
.RS
New: Signature Packet(tag 2)(63 bytes)
.RE
.PP
.B Old:
or
.B New:
is the format of the packet header:
.B Old:
is the legacy format (also used by PGP 2.x) and
.B New:
is the OpenPGP format.
This is independent of the version of the packet itself.
.B (tag 2)
is the packet type ID and
.B (63 bytes)
is the length of the packet body.
.PP
The indented lines are the fields of the packet body.
.B Ver 3 \- old,
.B Ver 4 \- new,
.B Ver 5 \- librepgp,
and
.B Ver 6 \- latest
are the versions of keys and signatures defined in RFC 1991,
RFC 4880, LibrePGP, and RFC 9580, respectively.
A number in parentheses, such as
.B (pub 17)
or
.BR "(hash 8)" ,
is the algorithm ID or the subpacket type ID defined in the RFCs and LibrePGP.
.B Hashed Sub:
and
.B Sub:
are subpackets in the hashed and unhashed areas of a signature.
.B ...
means that the data is omitted; use the options above to show it.
.\"
.SH SEE ALSO
.BR gpg (1),
.BR sq (1)
.PP
RFC 9580, RFC 4880, RFC 1991, draft-koch-librepgp (LibrePGP)
